<?php

/**
 * generator uses fof_render_item function from fof-render.php to generate static html files
 */
 
 $fof_no_login = true;

include_once("../fof-main.php");
include_once("../fof-render.php");
 
if (!fof_authenticate($_GET["user_name"], md5($_GET['user_password'] . $_GET['user_name']))) {
    echo "<strong>Authentication failed!</strong>";
    echo "</br>";
}


/**
 * Write html by tags
 *
 * @param string The path to write html
 * @param string The template file to use
 * @return null
 */

function write_html_by_tags($path, $template) {
    
    $users_result = fof_safe_query("select user_id, user_name from fof_user where user_id > 1");    
	
	while($user_row = fof_db_get_row($users_result)) {
	   
		$userId = $user_row['user_id'];
        $userName = $user_row['user_name'];

        $tags = fof_get_tags($userId);
    
        if ($tags) {
        
            $index = 0;
        
            echo "<strong>Generation static html files generated by tags...</strong>";
            echo "</br>";
            
            $thisdir = getcwd();
                
            if(!mkdir($thisdir."../../html/$userName" , 0777, true)) {
                echo "Failed to create directory - $userName ...";
                echo "</br>";
            }
            
            foreach($tags as $tag) {
                $tag_name = $tag['tag_name'];
                
                $result = fof_get_items($userId, $_GET['feed'], $tag_name, $_GET['when'], $which, $_GET['howmany'], $order, $_GET['search']);
            
                $server_name = $_SERVER['SERVER_NAME'];
                $user_name = $_GET['user_name'];
                $user_password = $_GET['user_password'];
                $theme = $_GET['theme'];
            
                $address = "http://$server_name/generator/generator.php?tag_name=$tag_name&user_name=$user_name&user_password=$user_password&fof_user=$userId&theme=$theme";
            
                foreach($result as $row) {

                    $sourcepage = $address;
                                
                    $targetfilename = "../html/$userName/$tag_name.html";
                    $tempfilename = "../html/$userName/$tag_name.tmp";                
                
                
                    $handle = fopen($sourcepage, "rb");
                    $contents = '';
                    while (!feof($handle)) {
                        $contents .= fread($handle, 8192);
                    }
                    fclose($handle);

                    $tempfile = fopen($tempfilename, 'w');
                    fwrite($tempfile, $contents);

                    copy($tempfilename, $targetfilename); 
                    //unlink($tempfilename);
 
                }
            
                $index++;
            }
            echo "<strong>Html files generated!</strong>";
            echo "</br>";
        } else {
            echo "<strong>No tags for user_id: $userName</strong>";
            echo "</br>";
        }
        
    }
}

if (!isset($_GET['tag_name'])) {
    
    write_html_by_tags("", "");
    
} else {
  
    if (fof_authenticate($_GET["user_name"], md5($_GET['user_password'] . $_GET['user_name']))) {
  
        $theme = $_GET['theme'];      
        include("$theme/header.php");
        
        $result = fof_get_items($_GET['fof_user'], $_GET['feed'], $_GET['tag_name'], $_GET['when'], $which, $_GET['howmany'], $order, $_GET['search']);
        
        foreach($result as $row) {
            fof_render_item($row);
        }
    
        include("footer.php");
        
    } else {
        echo "<strong>Authentication failed!</strong>";
    }
}

?>